#!/bin/bash
set -euo pipefail

# ───── Paths ─────
BASE_DIR="$HOME/production_apps"

# ───── Session & Windows ─────
SESSION="dev_env"

# Window Names
MAIN="WIP"

# ───── API Windows & Paths ─────
SERVICES=(
  "FRONTEND_SERVICE=$BASE_DIR/frontend_service"
  "PRODUCT_INFO_SERVICE=$BASE_DIR/product_info_service"
  "PALLET_SERVICE=$BASE_DIR/pallet_service"
  # "MANUFACTURING_SERVICE=$BASE_DIR/manufacturing_service"
  "LABEL_SERVICE=$BASE_DIR/label_service"
  "FILE_INTERFACE_SERVICE=$BASE_DIR/file_interface_service"
  # "DATA_PROCESSING_SERVICE=$BASE_DIR/data_processing_and_analysis_service"
)

# ───── Commands ─────
GIT_STATUS="git pull; git status"
FASTAPI_VENV="sh update.sh"

# ───── Create Session ─────
if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    tmux new-session -d -s "$SESSION" -n "$MAIN"

    # ───── Main Window Panes ─────
    tmux split-window -h -t "$SESSION:$MAIN"

        tmux select-pane -t "$SESSION:$MAIN.1"
        tmux send-keys -t "$SESSION:$MAIN.1" "cd \"$BASE_DIR/data_processing_and_analysis_service\"" C-m
        tmux send-keys -t "$SESSION:$MAIN.1" "$FASTAPI_VENV" C-m
        tmux send-keys -t "$SESSION:$MAIN.1" "docker attach analysis" C-m
        tmux select-pane -t "$SESSION:$MAIN.2"
        tmux send-keys -t "$SESSION:$MAIN.2" "cd \"$BASE_DIR/manufacturing_service \"" C-m
        tmux send-keys -t "$SESSION:$MAIN.2" "$FASTAPI_VENV" C-m
        tmux send-keys -t "$SESSION:$MAIN.2" "docker attach manufacturing" C-m

    # ───── API Windows ─────
    for entry in "${SERVICES[@]}"; do
        IFS='=' read -r API APP_PATH <<< "$entry"
        tmux new-window -t "$SESSION" -n "$API"
        tmux send-keys -t "$SESSION:$API" "cd \"$APP_PATH\"" C-m
        tmux send-keys -t "$SESSION:$API" "$GIT_STATUS" C-m
        tmux send-keys -t "$SESSION:$API" "$FASTAPI_VENV" C-m
    done

    tmux select-window -t "$SESSION:$MAIN"
fi

tmux attach -t "$SESSION"
