#!/bin/bash

# Session Name
SESSION="localRepoStatus"

# Check if the session already exists
tmux has-session -t $SESSION 2>/dev/null
if [ $? != 0 ]; then
    # Start a new session For linux repositories
    # dotfiles repo
    tmux new-session -d -s $SESSION -n 'Linux'
    tmux send-keys -t $SESSION:1 "cd $HOME/.dotfiles/" C-m
    tmux send-keys -t $SESSION:1 'git status' C-m
    # bin scripts repo
    tmux split-window -h -t $SESSION:1
    tmux send-keys -t $SESSION:1.2 "cd $HOME/.local/bin/" C-m
    tmux send-keys -t $SESSION:1.2 'git status' C-m

    # Dev folders Window
    # Nvim repo
    tmux new-window -t $SESSION -n 'Dev Config'
    tmux send-keys -t $SESSION:2 "cd $HOME/.nvim/" C-m
    tmux send-keys -t $SESSION:2 'git status' C-m
    # Docker Scripts
    tmux split-window -h -t $SESSION:2
    tmux send-keys -t $SESSION:2.2 "cd $HOME/.docker_scripts/" C-m
    tmux send-keys -t $SESSION:2.2 'git status' C-m
    # Ansible playbook
    tmux split-window -h -t $SESSION:2
    tmux send-keys -t $SESSION:2.3 "cd $HOME/.my_ansible/" C-m
    tmux send-keys -t $SESSION:2.3 'git status' C-m

    # New window for dev repos
    # Nvim repo
    tmux new-window -t $SESSION -n 'Dev Repos'
    tmux send-keys -t $SESSION:3 "cd $HOME/.fastapi/" C-m
    tmux send-keys -t $SESSION:3 "git checkout dev" C-m
    tmux send-keys -t $SESSION:3 'git status' C-m
    # Docker Scripts
    tmux split-window -h -t $SESSION:3
    tmux send-keys -t $SESSION:3.2 "cd $HOME/.reactapp/" C-m
    tmux send-keys -t $SESSION:3 "git checkout dev" C-m
    tmux send-keys -t $SESSION:3.2 'git status' C-m

: '
    # Dmenu Repo
    tmux new-window -t $SESSION -n 'Dev Repos'
    tmux send-keys -t $SESSION:3 "cd $HOME/.suckless/dmenu/" C-m
    tmux send-keys -t $SESSION:3 'git status' C-m
    # DWM Repo
    tmux split-window -h -t $SESSION:3
    tmux send-keys -t $SESSION:3.2 "cd $HOME/.suckless/dwm/" C-m
    tmux send-keys -t $SESSION:2.2 'git status' C-m
    # ST Repo
    tmux split-window -h -t $SESSION:3
    tmux send-keys -t $SESSION:3.3 "cd $HOME/.suckless/st/" C-m
    tmux send-keys -t $SESSION:2.3 'git status' C-m
'

    # Go back to Linux window
    tmux select-window -t $SESSION:1
fi
# Attach to the session
tmux attach -t $SESSION
